---
title: "STA 32 - HW 3"
author: "HANGSHI JIN"
output: html_document
---

###Problem 1
#Prob of T (1=MZ 2=MT 3=MP 4=FZ 5=FT 6=FP)
###a
```{r,echo=FALSE}
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 1 | one.draw == 4)/length(one.draw)
  
```

###b
```{r,echo=FALSE}
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 1 | one.draw == 2 | one.draw == 3 | one.draw == 4)/length(one.draw)
```

###c
```{r,echo=FALSE}
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 4 | one.draw == 5)/sum(one.draw == 1 | one.draw == 2 | one.draw == 4 | one.draw == 5)
```

###d
```{r,echo=FALSE}
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 5 | one.draw == 6)/length(one.draw)
```

###e
```{r,echo=FALSE}
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 1)/sum(one.draw == 1 | one.draw == 4)
```

###Problem 2

###a
```{r,echo=FALSE}
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(values,replace = FALSE)
})
sum(many.draws[1,] == "3" & many.draws[2,] == "3")/ncol(many.draws)
```

###b
```{r,echo=FALSE}
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(suits,replace = FALSE)
})
sum(many.draws[1,] == "S" & many.draws[2,] == "C")/ncol(many.draws)
```

###c
```{r,echo=FALSE}
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(values,replace = FALSE)
})
sum(many.draws[1,] == many.draws[2,])/ncol(many.draws)
```

###d
```{r,echo=FALSE}
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(deck,replace = FALSE)
})
sum(many.draws[1,] == c("S","Q") & many.draws[2,] == c("D","J"))/ncol(many.draws)

```

###Problem 3

###a
```{r,echo=FALSE}
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
sum(two.rolls == 0)/length(two.rolls)
```

###b
```{r,echo=FALSE}
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
sum(two.rolls >= 2)/length(two.rolls)
```

###c
```{r,echo=FALSE}
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
mean(two.rolls > 0)
sd(two.rolls > 0)
```

###d
```{r,echo=FALSE}
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
sd(two.rolls > 0)

```

###Problem 4

###a
```{r,echo=FALSE}
x = c(0,1,2,5,6,10)
p.x = c(0.50,0.05,0.10,0.05,0.05,0.15)
the.mean = sum(x*p.x)
the.var = sum(((x - the.mean)^2)*p.x)
v.return = c(the.mean,the.var)
names(v.return) = c("mean","variance")
v.return
```

###b
```{r,echo=FALSE}
x = seq(-20,0,2)
p.x = (1:11)/sum(1:11)
the.mean = sum(x*p.x)
the.var = sum(((x - the.mean)^2)*p.x)
v.return = c(the.mean, the.var)
names(v.return) = c("mean","variance")
v.return
```

###c
```{r,echo=FALSE}
x = 0:5
p.x = dbinom(0:5,5,0.50)
the.mean = sum(x*p.x)
the.var = sum(((x - the.mean)^2)*p.x)
v.return = c(the.mean, the.var)
names(v.return) = c("mean","variance")
v.return
```

##APPENDIX OF CODE
```
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 1 | one.draw == 4)/length(one.draw)
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 1 | one.draw == 2 | one.draw == 3 | one.draw == 4)/length(one.draw)
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 4 | one.draw == 5)/sum(one.draw == 1 | one.draw == 2 | one.draw == 4 | one.draw == 5)
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 5 | one.draw == 6)/length(one.draw)
one.draw = sample(c(1,2,3,4,5,6),10000,replace = TRUE, prob = c(77/400,77/400,33/200,63/400,9/100,81/400))
sum(one.draw == 1)/sum(one.draw == 1 | one.draw == 4)
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(values,replace = FALSE)
})
sum(many.draws[1,] == "3" & many.draws[2,] == "3")/ncol(many.draws)
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(suits,replace = FALSE)
})
sum(many.draws[1,] == "S" & many.draws[2,] == "C")/ncol(many.draws)
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(values,replace = FALSE)
})
sum(many.draws[1,] == many.draws[2,])/ncol(many.draws)
suits = rep(c("H","D","S","C"),times = 13)
values = rep(c("A",2:10,"J","Q","K"),times = 4)
deck = rbind(suits,values)
many.draws = sapply(1:100000, function(i){
  one.draw = sample(deck,replace = FALSE)
})
sum(many.draws[1,] == c("S","Q") & many.draws[2,] == c("D","J"))/ncol(many.draws)
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
sum(two.rolls == 0)/length(two.rolls)
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
sum(two.rolls >= 2)/length(two.rolls)
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
mean(two.rolls > 0)
sd(two.rolls > 0)
firstroll = sample(c(1:8),100000,replace = TRUE)
secondroll = sample(c(1:8),100000,replace = TRUE)
two.rolls = sample((2*firstroll - secondroll),replace = TRUE)
sd(two.rolls > 0)
x = c(0,1,2,5,6,10)
p.x = c(0.50,0.05,0.10,0.05,0.05,0.15)
the.mean = sum(x*p.x)
the.var = sum(((x - the.mean)^2)*p.x)
v.return = c(the.mean,the.var)
names(v.return) = c("mean","variance")
v.return
x = seq(-20,0,2)
p.x = (1:11)/sum(1:11)
the.mean = sum(x*p.x)
the.var = sum(((x - the.mean)^2)*p.x)
v.return = c(the.mean, the.var)
names(v.return) = c("mean","variance")
v.return
x = 0:5
p.x = dbinom(0:5,5,0.50)
the.mean = sum(x*p.x)
the.var = sum(((x - the.mean)^2)*p.x)
v.return = c(the.mean, the.var)
names(v.return) = c("mean","variance")
v.return
```
